/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-04 03:16:26
*/
/* FAULT METADATA: '{"shift":"shift","sin":"sin","order":[{"name":"_14_","ordinal":0,"width":1,"kind":"dff"},{"name":"_15_","ordinal":0,"width":1,"kind":"dff"},{"name":"_16_","ordinal":0,"width":1,"kind":"dff"},{"name":"_17_","ordinal":0,"width":1,"kind":"dff"},{"name":"Q","ordinal":0,"width":4,"kind":"output"}],"sout":"sout","boundaryCount":4,"internalCount":4}' END FAULT METADATA */
/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module counter(clk, rst, Q, sin, shift, sout, tck, test);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  output [3:0] Q;
  wire \__BoundaryScanRegister_output__0__.din ;
  wire \__BoundaryScanRegister_output__0__.sin ;
  wire \__BoundaryScanRegister_output__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.din ;
  wire \__BoundaryScanRegister_output__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.din ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__.__clk_source__ ;
  input clk;
  input rst;
  input shift;
  input sin;
  output sout;
  input tck;
  input test;
  INVX1 _34_ (
    .A(rst),
    .Y(_00_)
  );
  INVX1 _35_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .Y(_12_)
  );
  INVX1 _36_ (
    .A(\__BoundaryScanRegister_output__0__.sin ),
    .Y(_13_)
  );
  INVX1 _37_ (
    .A(shift),
    .Y(_14_)
  );
  INVX1 _38_ (
    .A(\__BoundaryScanRegister_output__1__.din ),
    .Y(_15_)
  );
  INVX1 _39_ (
    .A(\__BoundaryScanRegister_output__2__.din ),
    .Y(_16_)
  );
  INVX1 _40_ (
    .A(sin),
    .Y(_17_)
  );
  INVX1 _41_ (
    .A(clk),
    .Y(_18_)
  );
  NAND2X1 _42_ (
    .A(\__BoundaryScanRegister_output__0__.sin ),
    .B(shift),
    .Y(_19_)
  );
  OAI21X1 _43_ (
    .A(_12_),
    .B(shift),
    .C(_19_),
    .Y(_04_)
  );
  NAND2X1 _44_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__0__.sout ),
    .Y(_20_)
  );
  OAI21X1 _45_ (
    .A(shift),
    .B(_15_),
    .C(_20_),
    .Y(_05_)
  );
  NAND2X1 _46_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__1__.sout ),
    .Y(_21_)
  );
  OAI21X1 _47_ (
    .A(shift),
    .B(_16_),
    .C(_21_),
    .Y(_06_)
  );
  NAND2X1 _48_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__2__.sout ),
    .Y(_22_)
  );
  OAI21X1 _49_ (
    .A(_13_),
    .B(shift),
    .C(_22_),
    .Y(_07_)
  );
  NOR2X1 _50_ (
    .A(rst),
    .B(shift),
    .Y(_23_)
  );
  NAND2X1 _51_ (
    .A(_12_),
    .B(_23_),
    .Y(_24_)
  );
  OAI21X1 _52_ (
    .A(_14_),
    .B(_17_),
    .C(_24_),
    .Y(_08_)
  );
  AOI21X1 _53_ (
    .A(_14_),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(\__BoundaryScanRegister_output__0__.din ),
    .Y(_25_)
  );
  AOI21X1 _54_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(rst),
    .Y(_26_)
  );
  NOR2X1 _55_ (
    .A(shift),
    .B(_26_),
    .Y(_27_)
  );
  NOR2X1 _56_ (
    .A(_25_),
    .B(_27_),
    .Y(_09_)
  );
  AOI21X1 _57_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(\__BoundaryScanRegister_output__2__.din ),
    .Y(_28_)
  );
  NAND3X1 _58_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(\__BoundaryScanRegister_output__2__.din ),
    .Y(_29_)
  );
  NAND2X1 _59_ (
    .A(_23_),
    .B(_29_),
    .Y(_30_)
  );
  OAI22X1 _60_ (
    .A(_14_),
    .B(_15_),
    .C(_28_),
    .D(_30_),
    .Y(_10_)
  );
  AND2X1 _61_ (
    .A(_13_),
    .B(_29_),
    .Y(_31_)
  );
  OAI21X1 _62_ (
    .A(_13_),
    .B(_29_),
    .C(_23_),
    .Y(_32_)
  );
  OAI22X1 _63_ (
    .A(_14_),
    .B(_16_),
    .C(_31_),
    .D(_32_),
    .Y(_11_)
  );
  NAND2X1 _64_ (
    .A(tck),
    .B(test),
    .Y(_33_)
  );
  OAI21X1 _65_ (
    .A(_18_),
    .B(test),
    .C(_33_),
    .Y(\__uuf__.__clk_source__ )
  );
  INVX1 _66_ (
    .A(rst),
    .Y(_01_)
  );
  INVX1 _67_ (
    .A(rst),
    .Y(_02_)
  );
  INVX1 _68_ (
    .A(rst),
    .Y(_03_)
  );
  DFFSR _69_ (
    .CLK(tck),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__0__.sout ),
    .R(_00_),
    .S(1'h1)
  );
  DFFSR _70_ (
    .CLK(tck),
    .D(_05_),
    .Q(\__BoundaryScanRegister_output__1__.sout ),
    .R(_01_),
    .S(1'h1)
  );
  DFFSR _71_ (
    .CLK(tck),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__2__.sout ),
    .R(_02_),
    .S(1'h1)
  );
  DFFSR _72_ (
    .CLK(tck),
    .D(_07_),
    .Q(sout),
    .R(_03_),
    .S(1'h1)
  );
  DFFPOSX1 \__uuf__._14_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_08_),
    .Q(\__BoundaryScanRegister_output__0__.din )
  );
  DFFPOSX1 \__uuf__._15_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_09_),
    .Q(\__BoundaryScanRegister_output__1__.din )
  );
  DFFPOSX1 \__uuf__._16_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_10_),
    .Q(\__BoundaryScanRegister_output__2__.din )
  );
  DFFPOSX1 \__uuf__._17_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_11_),
    .Q(\__BoundaryScanRegister_output__0__.sin )
  );
  assign Q = { \__BoundaryScanRegister_output__0__.sin , \__BoundaryScanRegister_output__2__.din , \__BoundaryScanRegister_output__1__.din , \__BoundaryScanRegister_output__0__.din  };
endmodule

