/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1.1-8.10" *)
module counter(clk, rst, Q);
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:6.6-6.11|/build/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:6.6-6.11|/build/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "counter.v:1.55-1.56" *)
  output [3:0] Q;
  (* src = "counter.v:1.22-1.25" *)
  input clk;
  (* src = "counter.v:1.33-1.36" *)
  input rst;
  assign _02_[0] = ~Q[0];
  assign _03_[1] = Q[1] ^ Q[0];
  assign _00_ = ~(Q[1] & Q[0]);
  assign _03_[2] = ~(_00_ ^ Q[2]);
  assign _01_ = Q[2] & ~(_00_);
  assign _03_[3] = _01_ ^ Q[3];
  (* src = "counter.v:2.1-7.4" *)
  DFFPOSX1 _14_ (
    .CLK(clk),
    .D(_04_),
    .Q(Q[0])
  );
  (* src = "counter.v:2.1-7.4" *)
  DFFPOSX1 _15_ (
    .CLK(clk),
    .D(_05_),
    .Q(Q[1])
  );
  (* src = "counter.v:2.1-7.4" *)
  DFFPOSX1 _16_ (
    .CLK(clk),
    .D(_06_),
    .Q(Q[2])
  );
  (* src = "counter.v:2.1-7.4" *)
  DFFPOSX1 _17_ (
    .CLK(clk),
    .D(_07_),
    .Q(Q[3])
  );
  assign _04_ = rst ? 1'h0 : _02_[0];
  assign _05_ = rst ? 1'h0 : _03_[1];
  assign _06_ = rst ? 1'h0 : _03_[2];
  assign _07_ = rst ? 1'h0 : _03_[3];
  assign _02_[3:1] = Q[3:1];
  assign _03_[0] = _02_[0];
endmodule
